// CATÁLOGO DEMO — reemplazar con los datos reales importados desde Excel.
// Los precios son de referencia de mercado (MX, 2026) y NO son los de la empresa.
// Menú Ajustes > Importar catálogo para sustituirlo por completo.

const P = (o) => ({
  moneda: 'MXN',
  importado: false,
  leadTimeDias: 3,
  stock: 0,
  caracteristicas: [],
  ...o,
});

export const CATALOGO_DEMO = [
  // ---------------------------------------------------------------- DUELA DE INGENIERÍA
  P({ id: 'DI-ENC-09-190', sku: 'DI-ENC-09-190', nombreEn: 'Engineered Oak Flooring', nombre: 'Duela de ingeniería Encino Natural',
      categoria: 'duela-ingenieria', especie: 'Encino', espesorMm: 9, capaNobleMm: 0.6,
      anchoMm: 190, largoMm: 1220, acabado: 'Barnizado semi-mate UV', color: 'Miel natural',
      m2PorCaja: 2.32, precio: 780, unidad: 'm2', stock: 1840, leadTimeDias: 2,
      caracteristicas: ['Clic sin pegamento', 'Compatible con piso radiante'],
      notas: 'Capa noble delgada. No admite relijado. Uso residencial ligero.' }),

  P({ id: 'DI-ENC-12-190', sku: 'DI-ENC-12-190', nombreEn: 'Engineered Oak Flooring', nombre: 'Duela de ingeniería Encino Classic',
      categoria: 'duela-ingenieria', especie: 'Encino', espesorMm: 12, capaNobleMm: 2.5,
      anchoMm: 190, largoMm: 1900, acabado: 'Barnizado mate', color: 'Encino claro',
      m2PorCaja: 2.16, precio: 1120, unidad: 'm2', stock: 960, leadTimeDias: 3,
      caracteristicas: ['Admite 1 relijado', 'Compatible con piso radiante'] }),

  P({ id: 'DI-ENC-14-220-AC', sku: 'DI-ENC-14-220-AC', nombreEn: 'Oiled Engineered Oak Flooring', nombre: 'Duela de ingeniería Encino Premium Aceitado',
      categoria: 'duela-ingenieria', especie: 'Encino', espesorMm: 14, capaNobleMm: 3.0,
      anchoMm: 220, largoMm: 2200, acabado: 'Aceitado mate premium', color: 'Encino natural',
      m2PorCaja: 2.42, precio: 1690, unidad: 'm2', stock: 420, leadTimeDias: 5,
      caracteristicas: ['Aceite natural penetrante', 'Reparable en sitio', 'Admite 2 relijados'],
      notas: 'Acabado aceitado: mantenimiento cada 18-24 meses con aceite de la misma línea.' }),

  P({ id: 'DI-ENC-15-260-AH', sku: 'DI-ENC-15-260-AH', nombreEn: 'Smoked Wide-Plank Engineered Oak', nombre: 'Duela de ingeniería Encino Ahumado Extra Ancha',
      categoria: 'duela-ingenieria', especie: 'Encino', espesorMm: 15, capaNobleMm: 4.0,
      anchoMm: 260, largoMm: 2400, acabado: 'Cepillado y aceitado', color: 'Ahumado profundo',
      m2PorCaja: 2.50, precio: 2150, unidad: 'm2', stock: 180, importado: true,
      origen: 'España', leadTimeDias: 45,
      caracteristicas: ['Ahumado en cámara', 'Cepillado a mano', 'Admite 3 relijados'] }),

  P({ id: 'DI-ROB-14-220', sku: 'DI-ROB-14-220', nombreEn: 'European Oak Engineered Flooring', nombre: 'Duela de ingeniería Roble Europeo',
      categoria: 'duela-ingenieria', especie: 'Roble', espesorMm: 14, capaNobleMm: 3.5,
      anchoMm: 220, largoMm: 2200, acabado: 'Aceitado mate premium', color: 'Roble blanqueado',
      m2PorCaja: 2.42, precio: 1980, unidad: 'm2', stock: 260, importado: true,
      origen: 'Croacia', leadTimeDias: 50,
      caracteristicas: ['Grado Select', 'Certificación FSC', 'Aceite natural'] }),

  P({ id: 'DI-ROB-12-190', sku: 'DI-ROB-12-190', nombreEn: 'American White Oak Engineered Flooring', nombre: 'Duela de ingeniería Roble Blanco Americano',
      categoria: 'duela-ingenieria', especie: 'Roble', espesorMm: 12, capaNobleMm: 2.5,
      anchoMm: 190, largoMm: 1900, acabado: 'Barnizado satinado', color: 'Roble miel',
      m2PorCaja: 2.16, precio: 1340, unidad: 'm2', stock: 540, importado: true,
      origen: 'Estados Unidos', leadTimeDias: 28 }),

  P({ id: 'DI-NOG-14-190', sku: 'DI-NOG-14-190', nombreEn: 'American Walnut Engineered Flooring', nombre: 'Duela de ingeniería Nogal Americano',
      categoria: 'duela-ingenieria', especie: 'Nogal', espesorMm: 14, capaNobleMm: 3.0,
      anchoMm: 190, largoMm: 1900, acabado: 'Aceitado mate premium', color: 'Nogal chocolate',
      m2PorCaja: 2.16, precio: 2340, unidad: 'm2', stock: 140, importado: true,
      origen: 'Estados Unidos', leadTimeDias: 35,
      caracteristicas: ['Veta cerrada', 'Alta estabilidad dimensional'] }),

  P({ id: 'DI-MAP-12-150', sku: 'DI-MAP-12-150', nombreEn: 'Canadian Maple Engineered Flooring', nombre: 'Duela de ingeniería Maple Canadiense',
      categoria: 'duela-ingenieria', especie: 'Maple', espesorMm: 12, capaNobleMm: 2.5,
      anchoMm: 150, largoMm: 1800, acabado: 'Barnizado mate', color: 'Maple crema',
      m2PorCaja: 1.98, precio: 1560, unidad: 'm2', stock: 220, importado: true,
      origen: 'Canadá', leadTimeDias: 32 }),

  P({ id: 'DI-PIN-12-190', sku: 'DI-PIN-12-190', nombreEn: 'Nordic Pine Engineered Flooring', nombre: 'Duela de ingeniería Pino Nórdico',
      categoria: 'duela-ingenieria', especie: 'Pino', espesorMm: 12, capaNobleMm: 2.5,
      anchoMm: 190, largoMm: 1800, acabado: 'Natural mate', color: 'Pino claro',
      m2PorCaja: 2.16, precio: 560, unidad: 'm2', stock: 1280, leadTimeDias: 2,
      caracteristicas: ['Económico', 'Madera blanda: uso residencial ligero'],
      notas: 'Pino marca con facilidad. No recomendado en áreas de alto tránsito.' }),

  P({ id: 'DI-PIN-20-260', sku: 'DI-PIN-20-260', nombreEn: 'Solid Rustic Pine Wide Plank', nombre: 'Duela maciza Pino Rústico Extra Ancha',
      categoria: 'duela-ingenieria', especie: 'Pino', espesorMm: 20, capaNobleMm: 20,
      anchoMm: 260, largoMm: 2400, acabado: 'Cepillado y aceitado', color: 'Pino envejecido',
      m2PorCaja: 1.87, precio: 940, unidad: 'm2', stock: 380, leadTimeDias: 7,
      caracteristicas: ['Madera maciza', 'Estilo rústico', 'Relijable indefinidamente'] }),

  P({ id: 'DI-TZA-14-190', sku: 'DI-TZA-14-190', nombreEn: 'Caribbean Walnut Engineered Flooring', nombre: 'Duela de ingeniería Tzalam Mexicano',
      categoria: 'duela-ingenieria', especie: 'Tzalam', espesorMm: 14, capaNobleMm: 3.0,
      anchoMm: 190, largoMm: 1800, acabado: 'Aceitado mate premium', color: 'Tzalam tabaco',
      m2PorCaja: 2.16, precio: 1780, unidad: 'm2', stock: 310, leadTimeDias: 10,
      caracteristicas: ['Madera nacional', 'Alta dureza Janka'] }),

  P({ id: 'DI-BAM-14-125', sku: 'DI-BAM-14-125', nombreEn: 'Strand Woven Bamboo Flooring', nombre: 'Duela de bambú prensado Strand Woven',
      categoria: 'duela-ingenieria', especie: 'Bambú', espesorMm: 14, capaNobleMm: 14,
      anchoMm: 125, largoMm: 1850, acabado: 'Barnizado mate', color: 'Caramelo',
      m2PorCaja: 2.31, precio: 890, unidad: 'm2', stock: 640, importado: true,
      origen: 'China', leadTimeDias: 40,
      caracteristicas: ['Dureza superior al encino', 'Material renovable'] }),

  // ---------------------------------------------------------------- SPC
  P({ id: 'SPC-04-180', sku: 'SPC-04-180', nombreEn: 'SPC Rigid Core Vinyl Plank', nombre: 'Piso SPC Essential 4 mm',
      categoria: 'spc', especie: 'Símil encino', espesorMm: 4, anchoMm: 180, largoMm: 1220,
      acabado: 'Textura sincronizada mate', color: 'Encino gris', capaUsoMil: 12,
      m2PorCaja: 2.63, precio: 320, unidad: 'm2', stock: 3200, leadTimeDias: 2,
      caracteristicas: ['100% impermeable', 'Clic sin pegamento', 'Uso residencial'] }),

  P({ id: 'SPC-05-228', sku: 'SPC-05-228', nombreEn: 'SPC Rigid Core Vinyl Plank', nombre: 'Piso SPC Signature 5 mm',
      categoria: 'spc', especie: 'Símil roble', espesorMm: 5, anchoMm: 228, largoMm: 1524,
      acabado: 'Textura sincronizada mate', color: 'Roble natural', capaUsoMil: 20,
      m2PorCaja: 2.23, precio: 420, unidad: 'm2', stock: 2450, leadTimeDias: 2,
      caracteristicas: ['100% impermeable', 'Uso comercial ligero', 'Capa 20 mil'] }),

  P({ id: 'SPC-06-228-IXPE', sku: 'SPC-06-228-IXPE', nombreEn: 'SPC Vinyl Plank with IXPE Acoustic Backing', nombre: 'Piso SPC Acoustic 6 mm con IXPE',
      categoria: 'spc', especie: 'Símil encino', espesorMm: 6, anchoMm: 228, largoMm: 1524,
      acabado: 'Cepillado profundo mate', color: 'Encino ahumado', capaUsoMil: 22,
      m2PorCaja: 2.23, precio: 520, unidad: 'm2', stock: 1680, importado: true,
      origen: 'China', leadTimeDias: 38,
      caracteristicas: ['100% impermeable', 'Respaldo acústico IXPE 1.5 mm', 'Uso comercial'] }),

  P({ id: 'SPC-08-300', sku: 'SPC-08-300', nombreEn: 'Commercial Grade SPC Vinyl Plank', nombre: 'Piso SPC Hotel Grade 8 mm',
      categoria: 'spc', especie: 'Símil roble', espesorMm: 8, anchoMm: 300, largoMm: 1830,
      acabado: 'Textura registrada mate', color: 'Roble carbón', capaUsoMil: 30,
      m2PorCaja: 2.20, precio: 680, unidad: 'm2', stock: 890, importado: true,
      origen: 'Corea del Sur', leadTimeDias: 42,
      caracteristicas: ['100% impermeable', 'Uso comercial pesado', 'Garantía 25 años',
                        'Clasificación B1 fuego'] }),

  P({ id: 'SPC-05-610-PIEDRA', sku: 'SPC-05-610-PIEDRA', nombreEn: 'SPC Stone-Look Tile', nombre: 'Piso SPC formato piedra 60x60',
      categoria: 'spc', especie: 'Símil mármol', espesorMm: 5, anchoMm: 610, largoMm: 610,
      acabado: 'Mate texturizado', color: 'Mármol Calacatta', capaUsoMil: 20,
      m2PorCaja: 2.23, precio: 480, unidad: 'm2', stock: 720, leadTimeDias: 4,
      caracteristicas: ['100% impermeable', 'Apto para baños'] }),

  // ---------------------------------------------------------------- LAMINADO
  P({ id: 'LAM-08-AC4', sku: 'LAM-08-AC4', nombreEn: 'AC4 Laminate Flooring', nombre: 'Piso laminado 8 mm AC4',
      categoria: 'laminado', especie: 'Símil encino', espesorMm: 8, anchoMm: 192, largoMm: 1285,
      acabado: 'Mate poro sincronizado', color: 'Encino natural',
      m2PorCaja: 2.22, precio: 245, unidad: 'm2', stock: 4100, leadTimeDias: 2,
      caracteristicas: ['AC4 uso comercial ligero', 'Clic sin pegamento'],
      notas: 'No es impermeable. Descartar en baños y cocinas expuestas.' }),

  P({ id: 'LAM-12-AC5', sku: 'LAM-12-AC5', nombreEn: 'AC5 Water-Resistant Laminate Flooring', nombre: 'Piso laminado 12 mm AC5 hidrorresistente',
      categoria: 'laminado', especie: 'Símil roble', espesorMm: 12, anchoMm: 244, largoMm: 1380,
      acabado: 'Cepillado mate', color: 'Roble gris humo',
      m2PorCaja: 1.68, precio: 410, unidad: 'm2', stock: 1560, importado: true,
      origen: 'Alemania', leadTimeDias: 30,
      caracteristicas: ['AC5 uso comercial', 'Núcleo hidrorresistente 24 h', 'Garantía 20 años'] }),

  P({ id: 'LAM-10-AC4-XL', sku: 'LAM-10-AC4-XL', nombreEn: 'XL Format Laminate Flooring', nombre: 'Piso laminado 10 mm formato XL',
      categoria: 'laminado', especie: 'Símil encino', espesorMm: 10, anchoMm: 244, largoMm: 2050,
      acabado: 'Mate profundo', color: 'Encino blanqueado',
      m2PorCaja: 2.00, precio: 340, unidad: 'm2', stock: 980, leadTimeDias: 5,
      caracteristicas: ['AC4', 'Tabla extra larga', 'Bisel en 4 lados'] }),

  // ---------------------------------------------------------------- DECK
  P({ id: 'DECK-WPC-140', sku: 'DECK-WPC-140', nombreEn: 'WPC Composite Decking', nombre: 'Deck WPC coextruido 140 mm',
      categoria: 'deck', especie: 'Compuesto WPC', espesorMm: 23, anchoMm: 140, largoMm: 2900,
      acabado: 'Cepillado antiderrapante', color: 'Teca',
      m2PorCaja: 2.03, precio: 890, unidad: 'm2', stock: 620, importado: true,
      origen: 'China', leadTimeDias: 45,
      caracteristicas: ['Exterior', 'Antiderrapante', 'Sin mantenimiento', 'Anti-UV'] }),

  P({ id: 'DECK-WPC-160-CO', sku: 'DECK-WPC-160-CO', nombreEn: 'Co-Extruded WPC Decking', nombre: 'Deck WPC coextruido premium 160 mm',
      categoria: 'deck', especie: 'Compuesto WPC', espesorMm: 25, anchoMm: 160, largoMm: 3600,
      acabado: 'Veta profunda antiderrapante', color: 'Gris antracita',
      m2PorCaja: 2.30, precio: 1180, unidad: 'm2', stock: 340, importado: true,
      origen: 'China', leadTimeDias: 45,
      caracteristicas: ['Exterior', 'Antiderrapante', 'Garantía 15 años', 'Apto alberca'] }),

  P({ id: 'DECK-IPE-90', sku: 'DECK-IPE-90', nombreEn: 'Solid Ipe Hardwood Decking', nombre: 'Deck de Ipê macizo 90 mm',
      categoria: 'deck', especie: 'Ipê', espesorMm: 21, anchoMm: 90, largoMm: 2100,
      acabado: 'Cepillado natural', color: 'Ipê oliva',
      m2PorCaja: 1.51, precio: 2450, unidad: 'm2', stock: 120, importado: true,
      origen: 'Brasil', leadTimeDias: 60,
      caracteristicas: ['Exterior', 'Clase 1 durabilidad', 'Vida útil 25+ años'],
      notas: 'Requiere aceite de exteriores cada 12 meses para conservar el tono.' }),

  P({ id: 'DECK-TEC-100', sku: 'DECK-TEC-100', nombreEn: 'Burmese Teak Decking', nombre: 'Deck de Teca birmana 100 mm',
      categoria: 'deck', especie: 'Teca', espesorMm: 20, anchoMm: 100, largoMm: 2400,
      acabado: 'Cepillado natural', color: 'Teca dorada',
      m2PorCaja: 1.44, precio: 3200, unidad: 'm2', stock: 68, importado: true,
      origen: 'Indonesia', leadTimeDias: 70,
      caracteristicas: ['Exterior', 'Uso náutico', 'Aceites naturales'] }),

  // ---------------------------------------------------------------- PORCELANATO
  P({ id: 'POR-60x60-MATE', sku: 'POR-60x60-MATE', nombreEn: 'Rectified Matte Porcelain Tile', nombre: 'Porcelanato 60x60 rectificado mate',
      categoria: 'porcelanato', especie: 'Porcelánico', espesorMm: 9, anchoMm: 600, largoMm: 600,
      acabado: 'Mate rectificado', color: 'Cemento gris',
      m2PorCaja: 1.44, precio: 380, unidad: 'm2', stock: 2800, leadTimeDias: 3,
      caracteristicas: ['Rectificado', 'Absorción <0.5%', 'Interior'] }),

  P({ id: 'POR-60x120-REC', sku: 'POR-60x120-REC', nombreEn: 'Rectified Large Format Porcelain Tile', nombre: 'Porcelanato 60x120 rectificado',
      categoria: 'porcelanato', especie: 'Porcelánico', espesorMm: 10, anchoMm: 600, largoMm: 1200,
      acabado: 'Mate sedoso rectificado', color: 'Mármol Statuario',
      m2PorCaja: 1.44, precio: 620, unidad: 'm2', stock: 1240, importado: true,
      origen: 'Italia', leadTimeDias: 40,
      caracteristicas: ['Rectificado', 'Gran formato', 'Junta 1.5 mm'] }),

  P({ id: 'POR-120x120', sku: 'POR-120x120', nombreEn: 'Polished Large Format Porcelain Slab', nombre: 'Porcelanato 120x120 gran formato',
      categoria: 'porcelanato', especie: 'Porcelánico', espesorMm: 11, anchoMm: 1200, largoMm: 1200,
      acabado: 'Pulido brillante', color: 'Calacatta oro',
      m2PorCaja: 2.88, precio: 880, unidad: 'm2', stock: 460, importado: true,
      origen: 'Italia', leadTimeDias: 45,
      caracteristicas: ['Gran formato', 'Requiere nivelador de cuñas', 'Sustrato plano <2 mm'],
      notas: 'Gran formato: la merma sube y la mano de obra requiere dos instaladores.' }),

  P({ id: 'POR-20x120-MAD', sku: 'POR-20x120-MAD', nombreEn: 'Wood-Look Porcelain Plank', nombre: 'Porcelanato símil madera 20x120',
      categoria: 'porcelanato', especie: 'Porcelánico', espesorMm: 9, anchoMm: 200, largoMm: 1200,
      acabado: 'Textura madera mate', color: 'Encino miel',
      m2PorCaja: 1.44, precio: 540, unidad: 'm2', stock: 1680, leadTimeDias: 4,
      caracteristicas: ['Apto exterior cubierto', 'Antiderrapante R10'] }),

  P({ id: 'POR-30x60-ANTID', sku: 'POR-30x60-ANTID', nombreEn: 'R11 Anti-Slip Porcelain Tile', nombre: 'Porcelanato antiderrapante R11 30x60',
      categoria: 'porcelanato', especie: 'Porcelánico', espesorMm: 9, anchoMm: 300, largoMm: 600,
      acabado: 'Estructurado antiderrapante', color: 'Piedra arena',
      m2PorCaja: 1.44, precio: 460, unidad: 'm2', stock: 940, leadTimeDias: 3,
      caracteristicas: ['Antiderrapante R11', 'Apto alberca', 'Exterior'] }),

  // ---------------------------------------------------------------- CORTINAS (precio por metro lineal de tela)
  P({ id: 'CORT-BO-HOT-290', sku: 'CORT-BO-HOT-290', nombreEn: 'Flame Retardant Hotel Blackout Drapery', nombre: 'Blackout hotelero retardante de flama',
      categoria: 'cortina', tela: 'Poliéster FR trilaminado', anchoRolloM: 2.90,
      acabado: 'Mate', color: 'Arena', precio: 340, unidad: 'ml', stock: 1400,
      importado: true, origen: 'Turquía', leadTimeDias: 35,
      caracteristicas: ['Retardante de flama NFPA 701', 'Opacidad 100%', 'Uso hotelero',
                        'Lavable en seco'],
      notas: 'Certificado NFPA 701 requerido por la mayoría de las cadenas hoteleras.' }),

  P({ id: 'CORT-BO-3P-280', sku: 'CORT-BO-3P-280', nombreEn: '3-Pass Blackout Curtain Fabric', nombre: 'Blackout 3 pasadas residencial',
      categoria: 'cortina', tela: 'Poliéster 3 pasadas', anchoRolloM: 2.80,
      acabado: 'Mate', color: 'Blanco hueso', precio: 280, unidad: 'ml', stock: 2100,
      leadTimeDias: 3,
      caracteristicas: ['Opacidad 100%', 'Aislante térmico'] }),

  P({ id: 'CORT-VELO-300', sku: 'CORT-VELO-300', nombreEn: 'Sheer Voile Curtain Fabric', nombre: 'Velo translúcido de altura',
      categoria: 'cortina', tela: 'Voile de poliéster', anchoRolloM: 3.00,
      acabado: 'Translúcido', color: 'Marfil', precio: 180, unidad: 'ml', stock: 3200,
      leadTimeDias: 2,
      caracteristicas: ['Translúcido', 'Caída fluida', 'Lavable'] }),

  P({ id: 'CORT-LINO-280', sku: 'CORT-LINO-280', nombreEn: 'Belgian Linen Drapery Fabric', nombre: 'Lino belga 100% natural',
      categoria: 'cortina', tela: 'Lino 100%', anchoRolloM: 2.80,
      acabado: 'Textura natural', color: 'Lino crudo', precio: 520, unidad: 'ml', stock: 480,
      importado: true, origen: 'Bélgica', leadTimeDias: 45,
      caracteristicas: ['Fibra natural', 'Semi-translúcido', 'Alta gama'],
      notas: 'El lino natural encoge. Preencogido obligatorio antes de confección.' }),

  P({ id: 'CORT-JACQ-140', sku: 'CORT-JACQ-140', nombreEn: 'Damask Jacquard Drapery Fabric', nombre: 'Jacquard damasco',
      categoria: 'cortina', tela: 'Jacquard poliéster-viscosa', anchoRolloM: 1.40,
      acabado: 'Satinado', color: 'Oro viejo', precio: 460, unidad: 'ml', stock: 620,
      importado: true, origen: 'España', leadTimeDias: 40,
      caracteristicas: ['Rapport 64 cm', 'Uso decorativo'],
      notas: 'Con rapport hay que cuadrar el dibujo entre paños. Sube la merma de tela.' }),

  P({ id: 'CORT-TERC-140', sku: 'CORT-TERC-140', nombreEn: 'Cotton Velvet Drapery Fabric', nombre: 'Terciopelo de algodón',
      categoria: 'cortina', tela: 'Terciopelo algodón', anchoRolloM: 1.40,
      acabado: 'Aterciopelado', color: 'Verde botella', precio: 680, unidad: 'ml', stock: 280,
      importado: true, origen: 'Italia', leadTimeDias: 50,
      caracteristicas: ['Aislante acústico', 'Alta gama', 'Dirección de pelo'] }),

  P({ id: 'CORT-DIM-280', sku: 'CORT-DIM-280', nombreEn: 'Dimout Semi-Opaque Curtain Fabric', nombre: 'Dimout semi-opaco de altura',
      categoria: 'cortina', tela: 'Poliéster dimout', anchoRolloM: 2.80,
      acabado: 'Mate', color: 'Gris perla', precio: 240, unidad: 'ml', stock: 1850,
      leadTimeDias: 3,
      caracteristicas: ['Opacidad 85%', 'Antiestático'] }),

  // ---------------------------------------------------------------- PERSIANAS (precio por m²)
  P({ id: 'PER-ENR-SCR3', sku: 'PER-ENR-SCR3', nombreEn: '3% Solar Screen Roller Shade', nombre: 'Persiana enrollable Screen 3%',
      categoria: 'persiana', tela: 'Fibra de vidrio + PVC', acabado: 'Screen 3%',
      color: 'Gris carbón', precio: 760, unidad: 'm2', stock: 0, leadTimeDias: 12,
      caracteristicas: ['Control solar', 'Preserva la vista al exterior', 'Retardante de flama'],
      notas: 'Fabricación a medida. 12 días hábiles desde confirmación de medidas.' }),

  P({ id: 'PER-ENR-SCR5', sku: 'PER-ENR-SCR5', nombreEn: '5% Solar Screen Roller Shade', nombre: 'Persiana enrollable Screen 5%',
      categoria: 'persiana', tela: 'Fibra de vidrio + PVC', acabado: 'Screen 5%',
      color: 'Blanco lino', precio: 700, unidad: 'm2', stock: 0, leadTimeDias: 12,
      caracteristicas: ['Control solar', 'Mayor luminosidad', 'Retardante de flama'] }),

  P({ id: 'PER-ENR-BO', sku: 'PER-ENR-BO', nombreEn: 'Blackout Roller Shade', nombre: 'Persiana enrollable Blackout',
      categoria: 'persiana', tela: 'Poliéster blackout', acabado: 'Blackout',
      color: 'Arena', precio: 840, unidad: 'm2', stock: 0, leadTimeDias: 12,
      caracteristicas: ['Opacidad 100%', 'Uso hotelero', 'Cenefa incluida'] }),

  P({ id: 'PER-SHEER-EL', sku: 'PER-SHEER-EL', nombreEn: 'Sheer Shade', nombre: 'Persiana Sheer Elegance',
      categoria: 'persiana', tela: 'Poliéster doble visión', acabado: 'Sheer',
      color: 'Champagne', precio: 1450, unidad: 'm2', stock: 0, importado: true,
      origen: 'Estados Unidos', leadTimeDias: 30,
      caracteristicas: ['Doble visión', 'Gradación de luz', 'Alta gama'] }),

  P({ id: 'PER-PANEL-JAP', sku: 'PER-PANEL-JAP', nombreEn: 'Japanese Panel Track Blind', nombre: 'Panel japonés riel de 4 vías',
      categoria: 'persiana', tela: 'Poliéster texturizado', acabado: 'Panel deslizante',
      color: 'Beige', precio: 1180, unidad: 'm2', stock: 0, leadTimeDias: 15,
      caracteristicas: ['Ideal para ventanales', 'Riel de aluminio 4 vías'] }),

  P({ id: 'PER-MAD-50', sku: 'PER-MAD-50', nombreEn: '50 mm Wood Venetian Blind', nombre: 'Persiana de madera 50 mm',
      categoria: 'persiana', tela: 'Basswood', acabado: 'Barnizado',
      color: 'Nogal', precio: 1890, unidad: 'm2', stock: 0, importado: true,
      origen: 'Estados Unidos', leadTimeDias: 35,
      caracteristicas: ['Madera natural', 'Cinta decorativa', 'Alta gama'],
      notas: 'No recomendada en baños ni zonas de humedad constante.' }),

  P({ id: 'PER-CEL-BO', sku: 'PER-CEL-BO', nombreEn: 'Blackout Cellular Honeycomb Shade', nombre: 'Persiana celular panal Blackout',
      categoria: 'persiana', tela: 'Poliéster celular doble', acabado: 'Blackout',
      color: 'Blanco', precio: 1620, unidad: 'm2', stock: 0, importado: true,
      origen: 'Estados Unidos', leadTimeDias: 30,
      caracteristicas: ['Aislante térmico R-value 3.2', 'Opacidad 100%', 'Sin cordones'] }),

  P({ id: 'PER-VERT-89', sku: 'PER-VERT-89', nombreEn: '89 mm Vertical Blind', nombre: 'Persiana vertical 89 mm',
      categoria: 'persiana', tela: 'Poliéster', acabado: 'Lamas verticales',
      color: 'Gris claro', precio: 620, unidad: 'm2', stock: 0, leadTimeDias: 10,
      caracteristicas: ['Económica', 'Ideal para oficinas', 'Lavable'] }),

  // ---------------------------------------------------------------- ACCESORIOS
  P({ id: 'ACC-ZOC-MDF', sku: 'ACC-ZOC-MDF', nombreEn: 'MDF Veneered Baseboard', nombre: 'Zoclo MDF enchapado 10 cm',
      categoria: 'accesorio', acabado: 'Enchapado a juego', color: 'Variable',
      precio: 145, unidad: 'ml', stock: 2400, leadTimeDias: 3,
      caracteristicas: ['Tramos de 2.40 m'] }),

  P({ id: 'ACC-ZOC-MAC', sku: 'ACC-ZOC-MAC', nombreEn: 'Solid Oak Baseboard', nombre: 'Zoclo macizo de encino 12 cm',
      categoria: 'accesorio', acabado: 'Aceitado a juego', color: 'Encino',
      precio: 260, unidad: 'ml', stock: 860, leadTimeDias: 7,
      caracteristicas: ['Madera maciza', 'Tramos de 2.40 m'] }),

  P({ id: 'ACC-PERF-TRA', sku: 'ACC-PERF-TRA', nombreEn: 'Aluminum Transition Profile', nombre: 'Perfil de transición de aluminio',
      categoria: 'accesorio', acabado: 'Anodizado', color: 'Champagne',
      precio: 320, unidad: 'pza', stock: 480, leadTimeDias: 3,
      caracteristicas: ['Tramo de 0.90 m'] }),

  P({ id: 'ACC-UNDER-3', sku: 'ACC-UNDER-3', nombreEn: 'Underlayment with Vapor Barrier', nombre: 'Barrera de vapor con espuma acústica 3 mm',
      categoria: 'accesorio', acabado: 'Rollo 15 m²', color: 'Azul',
      precio: 48, unidad: 'm2', stock: 5200, leadTimeDias: 2,
      caracteristicas: ['Barrera de vapor', 'Reducción acústica 19 dB'] }),

  P({ id: 'ACC-ADH-PU', sku: 'ACC-ADH-PU', nombreEn: 'Polyurethane Wood Flooring Adhesive', nombre: 'Adhesivo de poliuretano 20 kg',
      categoria: 'accesorio', acabado: 'Cubeta', color: 'Beige',
      precio: 2850, unidad: 'pza', stock: 140, importado: true, origen: 'Alemania',
      leadTimeDias: 25,
      caracteristicas: ['Rendimiento 18 m²/cubeta', 'Elastomérico'] }),

  P({ id: 'ACC-ACEITE', sku: 'ACC-ACEITE', nombreEn: 'Hardwax Maintenance Oil', nombre: 'Aceite de mantenimiento 1 L',
      categoria: 'accesorio', acabado: 'Mate natural', color: 'Incoloro',
      precio: 980, unidad: 'pza', stock: 220, importado: true, origen: 'Alemania',
      leadTimeDias: 25,
      caracteristicas: ['Rendimiento 40 m²/L', 'Para acabados aceitados'] }),

  P({ id: 'ACC-RIEL-MOT', sku: 'ACC-RIEL-MOT', nombreEn: 'Tubular Curtain Motor with Remote', nombre: 'Motor tubular para cortina con control',
      categoria: 'accesorio', acabado: 'Motorizado', color: 'Blanco',
      precio: 6800, unidad: 'pza', stock: 34, importado: true, origen: 'Francia',
      leadTimeDias: 30,
      caracteristicas: ['Radiofrecuencia', 'Compatible con domótica', 'Programable'] }),
];
