// Ampliación del catálogo de demostración.
// Mismo criterio que catalog-seed.js: precios de referencia de mercado (MX, 2026),
// nunca los de la empresa. Todo producto trae su nombre en inglés para que el
// asesor lo encuentre igual escribiendo "roller shade" que "persiana enrollable".

const P = (o) => ({
  moneda: 'MXN',
  importado: false,
  leadTimeDias: 3,
  stock: 0,
  caracteristicas: [],
  ...o,
});

export const CATALOGO_EXTRA = [
  // ---------------------------------------------------------------- MÁS DUELA
  P({ id: 'DI-ROB-20-300', sku: 'DI-ROB-20-300', nombreEn: 'Extra Wide European Oak Plank',
      nombre: 'Duela de ingeniería Roble Europeo 300 mm',
      categoria: 'duela-ingenieria', especie: 'Roble', espesorMm: 20, capaNobleMm: 6,
      anchoMm: 300, largoMm: 2800, acabado: 'Cepillado y aceitado', color: 'Roble arena',
      m2PorCaja: 1.68, precio: 3180, unidad: 'm2', stock: 92, importado: true,
      origen: 'Croacia', leadTimeDias: 60,
      caracteristicas: ['Tabla extra ancha', 'Admite 4 relijados', 'Grado Rústico Premium'],
      notas: 'Tabla de 2.80 m: revisar acceso y elevador antes de comprometer entrega.' }),

  P({ id: 'DI-ENC-14-190-ESP', sku: 'DI-ENC-14-190-ESP', nombreEn: 'Herringbone Engineered Oak Block',
      nombre: 'Duela de ingeniería Encino para espina de pescado',
      categoria: 'duela-ingenieria', especie: 'Encino', espesorMm: 14, capaNobleMm: 3,
      anchoMm: 90, largoMm: 450, acabado: 'Aceitado mate premium', color: 'Encino natural',
      m2PorCaja: 1.62, precio: 2280, unidad: 'm2', stock: 210, importado: true,
      origen: 'España', leadTimeDias: 45,
      caracteristicas: ['Corte para espina', 'Pieza izquierda y derecha', 'Admite 2 relijados'],
      notas: 'Viene en pares izquierda-derecha. Confirmar proporción al pedir.' }),

  P({ id: 'DI-CHE-14-190', sku: 'DI-CHE-14-190', nombreEn: 'American Cherry Engineered Flooring',
      nombre: 'Duela de ingeniería Cerezo Americano',
      categoria: 'duela-ingenieria', especie: 'Cerezo', espesorMm: 14, capaNobleMm: 3,
      anchoMm: 190, largoMm: 1900, acabado: 'Barnizado satinado', color: 'Cerezo rojizo',
      m2PorCaja: 2.16, precio: 2120, unidad: 'm2', stock: 130, importado: true,
      origen: 'Estados Unidos', leadTimeDias: 35,
      caracteristicas: ['Oscurece con la luz', 'Veta fina'],
      notas: 'El cerezo se oscurece con el sol. Advertirlo si hay ventanal grande.' }),

  P({ id: 'DI-PAR-15-220', sku: 'DI-PAR-15-220', nombreEn: 'Parota Engineered Flooring',
      nombre: 'Duela de ingeniería Parota Mexicana',
      categoria: 'duela-ingenieria', especie: 'Parota', espesorMm: 15, capaNobleMm: 4,
      anchoMm: 220, largoMm: 2000, acabado: 'Cepillado y aceitado', color: 'Parota miel',
      m2PorCaja: 2.20, precio: 1620, unidad: 'm2', stock: 260, leadTimeDias: 12,
      caracteristicas: ['Madera nacional', 'Veta ancha', 'Alta estabilidad'] }),

  P({ id: 'DI-ENC-12-190-BLA', sku: 'DI-ENC-12-190-BLA', nombreEn: 'White Washed Engineered Oak',
      nombre: 'Duela de ingeniería Encino Blanqueado',
      categoria: 'duela-ingenieria', especie: 'Encino', espesorMm: 12, capaNobleMm: 2.5,
      anchoMm: 190, largoMm: 1900, acabado: 'Aceitado blanco mate', color: 'Encino blanqueado',
      m2PorCaja: 2.16, precio: 1290, unidad: 'm2', stock: 480, leadTimeDias: 5,
      caracteristicas: ['Tono claro', 'Amplía visualmente', 'Admite 1 relijado'] }),

  // ---------------------------------------------------------------- MÁS SPC Y VINÍLICO
  P({ id: 'SPC-06-228-HER', sku: 'SPC-06-228-HER', nombreEn: 'SPC Herringbone Vinyl Plank',
      nombre: 'Piso SPC formato espina de pescado',
      categoria: 'spc', especie: 'Símil encino', espesorMm: 6, anchoMm: 152, largoMm: 610,
      acabado: 'Textura sincronizada mate', color: 'Encino miel', capaUsoMil: 20,
      m2PorCaja: 2.04, precio: 610, unidad: 'm2', stock: 780, importado: true,
      origen: 'China', leadTimeDias: 40,
      caracteristicas: ['100% impermeable', 'Corte para espina', 'Uso comercial ligero'] }),

  P({ id: 'LVT-03-PEG', sku: 'LVT-03-PEG', nombreEn: 'Glue Down Luxury Vinyl Tile (LVT)',
      nombre: 'Vinílico LVT pegado 3 mm',
      categoria: 'spc', especie: 'Símil roble', espesorMm: 3, anchoMm: 228, largoMm: 1219,
      acabado: 'Mate texturizado', color: 'Roble ceniza', capaUsoMil: 20,
      m2PorCaja: 3.34, precio: 340, unidad: 'm2', stock: 1900, leadTimeDias: 4,
      caracteristicas: ['Pegado total', 'Muy delgado', 'Ideal para remodelación'],
      notas: 'Al ir pegado copia el sustrato. Exige nivelación previa impecable.' }),

  P({ id: 'SPC-08-228-COM', sku: 'SPC-08-228-COM', nombreEn: 'Heavy Commercial SPC Plank',
      nombre: 'Piso SPC comercial pesado 8 mm capa 40 mil',
      categoria: 'spc', especie: 'Símil roble', espesorMm: 8, anchoMm: 228, largoMm: 1524,
      acabado: 'Textura profunda mate', color: 'Roble tabaco', capaUsoMil: 40,
      m2PorCaja: 2.23, precio: 890, unidad: 'm2', stock: 420, importado: true,
      origen: 'Corea del Sur', leadTimeDias: 45,
      caracteristicas: ['100% impermeable', 'Capa 40 mil', 'Garantía comercial 15 años',
                        'Clasificación B1 fuego'] }),

  // ---------------------------------------------------------------- MÁS PORCELANATO
  P({ id: 'POR-80x80-PUL', sku: 'POR-80x80-PUL', nombreEn: 'Polished Porcelain Tile 80x80',
      nombre: 'Porcelanato 80x80 pulido',
      categoria: 'porcelanato', especie: 'Porcelánico', espesorMm: 10, anchoMm: 800, largoMm: 800,
      acabado: 'Pulido brillante', color: 'Gris perla',
      m2PorCaja: 1.28, precio: 720, unidad: 'm2', stock: 640, importado: true,
      origen: 'España', leadTimeDias: 38,
      caracteristicas: ['Rectificado', 'Junta 2 mm', 'Interior'],
      notas: 'El pulido resbala en mojado. No usar en baño ni exterior.' }),

  P({ id: 'POR-120x260-SLAB', sku: 'POR-120x260-SLAB', nombreEn: 'Large Format Porcelain Slab',
      nombre: 'Placa de porcelánico 120x260 de 6 mm',
      categoria: 'porcelanato', especie: 'Porcelánico', espesorMm: 6, anchoMm: 1200, largoMm: 2600,
      acabado: 'Mate sedoso', color: 'Mármol Calacatta Viola',
      m2PorCaja: 3.12, precio: 1980, unidad: 'm2', stock: 42, importado: true,
      origen: 'Italia', leadTimeDias: 55,
      caracteristicas: ['Placa gran formato', 'Apto para muro y cubierta', 'Corte especializado'],
      notas: 'Requiere ventosas y dos instaladores. No se corta en obra sin equipo.' }),

  P({ id: 'POR-60x60-EXT', sku: 'POR-60x60-EXT', nombreEn: 'Outdoor Porcelain Paver 20 mm',
      nombre: 'Porcelanato de exterior 60x60 de 20 mm',
      categoria: 'porcelanato', especie: 'Porcelánico', espesorMm: 20, anchoMm: 600, largoMm: 600,
      acabado: 'Estructurado antiderrapante', color: 'Piedra gris',
      m2PorCaja: 0.72, precio: 980, unidad: 'm2', stock: 380, importado: true,
      origen: 'Italia', leadTimeDias: 42,
      caracteristicas: ['Antiderrapante R11', 'Exterior', 'Instalación en seco o pegado'] }),

  P({ id: 'POR-30x90-MUR', sku: 'POR-30x90-MUR', nombreEn: 'Wall Porcelain Tile 30x90',
      nombre: 'Porcelanato de muro 30x90',
      categoria: 'porcelanato', especie: 'Porcelánico', espesorMm: 9, anchoMm: 300, largoMm: 900,
      acabado: 'Mate con relieve', color: 'Blanco lino',
      m2PorCaja: 1.08, precio: 520, unidad: 'm2', stock: 860, leadTimeDias: 5,
      caracteristicas: ['Para muro', 'Relieve tridimensional'] }),

  // ---------------------------------------------------------------- MÁS DECK
  P({ id: 'DECK-BAM-140', sku: 'DECK-BAM-140', nombreEn: 'Thermo-Treated Bamboo Decking',
      nombre: 'Deck de bambú termotratado 140 mm',
      categoria: 'deck', especie: 'Bambú', espesorMm: 20, anchoMm: 140, largoMm: 1850,
      acabado: 'Cepillado natural', color: 'Bambú caramelo',
      m2PorCaja: 1.55, precio: 1480, unidad: 'm2', stock: 180, importado: true,
      origen: 'China', leadTimeDias: 48,
      caracteristicas: ['Exterior', 'Material renovable', 'Clase 1 durabilidad'] }),

  P({ id: 'DECK-ALU-160', sku: 'DECK-ALU-160', nombreEn: 'Aluminum Decking Plank',
      nombre: 'Deck de aluminio con acabado madera 160 mm',
      categoria: 'deck', especie: 'Aluminio', espesorMm: 25, anchoMm: 160, largoMm: 4000,
      acabado: 'Sublimado madera antiderrapante', color: 'Teca',
      m2PorCaja: 2.56, precio: 1980, unidad: 'm2', stock: 96, importado: true,
      origen: 'España', leadTimeDias: 50,
      caracteristicas: ['Exterior', 'No se pudre', 'Apto para alberca', 'Sin mantenimiento'] }),

  // ---------------------------------------------------------------- MÁS CORTINAS
  P({ id: 'CORT-FR-300-HOT', sku: 'CORT-FR-300-HOT', nombreEn: 'Flame Retardant Sheer Voile',
      nombre: 'Velo retardante de flama para hotelería',
      categoria: 'cortina', tela: 'Poliéster FR trevira CS', anchoRolloM: 3.00,
      acabado: 'Translúcido', color: 'Marfil', precio: 285, unidad: 'ml', stock: 980,
      importado: true, origen: 'Alemania', leadTimeDias: 42,
      caracteristicas: ['Retardante de flama NFPA 701', 'Trevira CS', 'Uso hotelero',
                        'Lavable a máquina'] }),

  P({ id: 'CORT-BLK-290-ACU', sku: 'CORT-BLK-290-ACU', nombreEn: 'Acoustic Blackout Drapery',
      nombre: 'Blackout acústico de alto gramaje',
      categoria: 'cortina', tela: 'Poliéster 480 g/m²', anchoRolloM: 2.90,
      acabado: 'Mate texturizado', color: 'Grafito', precio: 460, unidad: 'ml', stock: 520,
      importado: true, origen: 'Turquía', leadTimeDias: 38,
      caracteristicas: ['Opacidad 100%', 'Reducción acústica', 'Retardante de flama',
                        'Uso en salas de junta'] }),

  P({ id: 'CORT-SEDA-140', sku: 'CORT-SEDA-140', nombreEn: 'Faux Silk Drapery Fabric',
      nombre: 'Falsa seda con caída pesada',
      categoria: 'cortina', tela: 'Poliéster símil seda', anchoRolloM: 1.40,
      acabado: 'Satinado', color: 'Champagne', precio: 380, unidad: 'ml', stock: 740,
      leadTimeDias: 6,
      caracteristicas: ['Brillo suave', 'Buena caída'] }),

  P({ id: 'CORT-ALG-280', sku: 'CORT-ALG-280', nombreEn: 'Washed Cotton Drapery',
      nombre: 'Algodón lavado de altura',
      categoria: 'cortina', tela: 'Algodón 100% prelavado', anchoRolloM: 2.80,
      acabado: 'Mate natural', color: 'Blanco roto', precio: 340, unidad: 'ml', stock: 610,
      importado: true, origen: 'India', leadTimeDias: 40,
      caracteristicas: ['Fibra natural', 'Prelavado', 'Lavable en casa'] }),

  P({ id: 'CORT-OUT-300', sku: 'CORT-OUT-300', nombreEn: 'Outdoor Solution Dyed Acrylic',
      nombre: 'Tela acrílica de exterior teñida en masa',
      categoria: 'cortina', tela: 'Acrílico teñido en masa', anchoRolloM: 3.00,
      acabado: 'Mate', color: 'Arena', precio: 620, unidad: 'ml', stock: 340,
      importado: true, origen: 'Estados Unidos', leadTimeDias: 45,
      caracteristicas: ['Exterior', 'Anti-UV 5 años', 'Antihongos', 'Lavable con cloro'] }),

  // ---------------------------------------------------------------- MÁS PERSIANAS
  P({ id: 'PER-ROM-TELA', sku: 'PER-ROM-TELA', nombreEn: 'Roman Shade',
      nombre: 'Persiana romana con varillas',
      categoria: 'persiana', tela: 'Poliéster-lino', acabado: 'Pliegue plano',
      color: 'Lino natural', precio: 1680, unidad: 'm2', stock: 0, leadTimeDias: 18,
      caracteristicas: ['Aspecto de cortina', 'Ocupa poco espacio', 'A medida'] }),

  P({ id: 'PER-ALU-25', sku: 'PER-ALU-25', nombreEn: '25 mm Aluminum Venetian Blind',
      nombre: 'Persiana de aluminio 25 mm',
      categoria: 'persiana', tela: 'Aluminio lacado', acabado: 'Lamas horizontales',
      color: 'Plata mate', precio: 540, unidad: 'm2', stock: 0, leadTimeDias: 9,
      caracteristicas: ['Económica', 'Apta para baño y cocina', 'Fácil limpieza'] }),

  P({ id: 'PER-DUAL-ZEB', sku: 'PER-DUAL-ZEB', nombreEn: 'Zebra / Dual Roller Shade',
      nombre: 'Persiana enrollable doble visión (zebra)',
      categoria: 'persiana', tela: 'Poliéster bandas alternas', acabado: 'Doble visión',
      color: 'Gris humo', precio: 980, unidad: 'm2', stock: 0, leadTimeDias: 14,
      caracteristicas: ['Gradación de luz', 'Muy solicitada', 'Cadena o motor'] }),

  P({ id: 'PER-CEL-TD', sku: 'PER-CEL-TD', nombreEn: 'Top-Down Bottom-Up Cellular Shade',
      nombre: 'Persiana celular de doble apertura',
      categoria: 'persiana', tela: 'Poliéster celular', acabado: 'Translúcido',
      color: 'Arena', precio: 1980, unidad: 'm2', stock: 0, importado: true,
      origen: 'Estados Unidos', leadTimeDias: 32,
      caracteristicas: ['Abre de arriba y de abajo', 'Aislante térmico', 'Privacidad con luz'] }),

  P({ id: 'PER-EXT-SCR', sku: 'PER-EXT-SCR', nombreEn: 'Exterior Solar Screen Shade',
      nombre: 'Persiana screen de exterior con guías laterales',
      categoria: 'persiana', tela: 'Fibra de vidrio exterior', acabado: 'Screen 5% exterior',
      color: 'Bronce', precio: 2350, unidad: 'm2', stock: 0, importado: true,
      origen: 'Italia', leadTimeDias: 45,
      caracteristicas: ['Exterior', 'Guías laterales', 'Resistente a viento', 'Anti-UV'],
      notas: 'Baja hasta 8 °C la temperatura interior. Argumento fuerte en fachada poniente.' }),

  P({ id: 'PER-SHUT-89', sku: 'PER-SHUT-89', nombreEn: 'Plantation Shutter',
      nombre: 'Shutter de madera lama 89 mm',
      categoria: 'persiana', tela: 'Basswood', acabado: 'Lacado',
      color: 'Blanco', precio: 3450, unidad: 'm2', stock: 0, importado: true,
      origen: 'Estados Unidos', leadTimeDias: 50,
      caracteristicas: ['Alta gama', 'Se queda con la casa', 'Aislante'],
      notas: 'Se instala fijo al vano. Requiere levantamiento profesional milimétrico.' }),

  // ---------------------------------------------------------------- TOLDOS
  P({ id: 'TOL-COF-ACR', sku: 'TOL-COF-ACR', nombreEn: 'Full Cassette Retractable Awning',
      nombre: 'Toldo retráctil con cofre completo',
      categoria: 'toldo', tela: 'Acrílico teñido en masa', acabado: 'Cofre de aluminio',
      color: 'Arena', precio: 3850, unidad: 'm2', stock: 0, importado: true,
      origen: 'España', leadTimeDias: 45,
      caracteristicas: ['Exterior', 'Cofre protege la lona', 'Motorizable', 'Anti-UV'],
      notas: 'El cofre alarga la vida de la lona al doble. Vale la diferencia.' }),

  P({ id: 'TOL-BRA-ACR', sku: 'TOL-BRA-ACR', nombreEn: 'Open Folding Arm Awning',
      nombre: 'Toldo de brazos articulados sin cofre',
      categoria: 'toldo', tela: 'Acrílico teñido en masa', acabado: 'Abierto',
      color: 'Rayas crudo', precio: 2450, unidad: 'm2', stock: 0, leadTimeDias: 20,
      caracteristicas: ['Exterior', 'Económico', 'Motorizable'] }),

  P({ id: 'TOL-VER-SCR', sku: 'TOL-VER-SCR', nombreEn: 'Vertical Drop Screen Awning',
      nombre: 'Toldo vertical tipo caída con screen',
      categoria: 'toldo', tela: 'Screen de exterior', acabado: 'Caída vertical',
      color: 'Gris', precio: 2180, unidad: 'm2', stock: 0, leadTimeDias: 22,
      caracteristicas: ['Exterior', 'Conserva la vista', 'Ideal para terraza de restaurante'] }),

  P({ id: 'TOL-VELA-HDPE', sku: 'TOL-VELA-HDPE', nombreEn: 'Shade Sail',
      nombre: 'Vela de sombra tensada HDPE',
      categoria: 'toldo', tela: 'HDPE tejido', acabado: 'Tensada',
      color: 'Arena', precio: 1280, unidad: 'm2', stock: 0, leadTimeDias: 18,
      caracteristicas: ['Exterior', 'Permite paso de aire', 'Anti-UV 95%'] }),

  // ---------------------------------------------------------------- PÉRGOLAS
  P({ id: 'PER-BIO-ALU', sku: 'PER-BIO-ALU', nombreEn: 'Bioclimatic Louvered Pergola',
      nombre: 'Pérgola bioclimática de lamas orientables',
      categoria: 'pergola', tela: 'Aluminio extruido', acabado: 'Lamas motorizadas',
      color: 'Antracita', precio: 9800, unidad: 'm2', stock: 0, importado: true,
      origen: 'España', leadTimeDias: 60,
      caracteristicas: ['Exterior', 'Lamas orientables', 'Desagüe integrado', 'Motorizada'],
      notas: 'Requiere losa o dado de cimentación. Confirmar con estructurista si va sobre azotea.' }),

  P({ id: 'PER-FIJA-ALU', sku: 'PER-FIJA-ALU', nombreEn: 'Fixed Aluminum Pergola',
      nombre: 'Pérgola fija de aluminio con techo sólido',
      categoria: 'pergola', tela: 'Aluminio extruido', acabado: 'Techo panel sándwich',
      color: 'Blanco', precio: 6400, unidad: 'm2', stock: 0, importado: true,
      origen: 'China', leadTimeDias: 50,
      caracteristicas: ['Exterior', 'Aislante térmico', 'Impermeable'] }),

  P({ id: 'PER-MAD-LAM', sku: 'PER-MAD-LAM', nombreEn: 'Glulam Timber Pergola',
      nombre: 'Pérgola de madera laminada tratada',
      categoria: 'pergola', tela: 'Pino laminado autoclave', acabado: 'Barnizado exterior',
      color: 'Miel', precio: 5200, unidad: 'm2', stock: 0, leadTimeDias: 30,
      caracteristicas: ['Exterior', 'Madera tratada clase 4', 'Estética cálida'],
      notas: 'Requiere barnizado de mantenimiento cada 24 meses.' }),

  // ---------------------------------------------------------------- MÁS ACCESORIOS
  P({ id: 'ACC-MOLD-T', sku: 'ACC-MOLD-T', nombreEn: 'T-Molding Transition Strip',
      nombre: 'Moldura T de unión entre pisos',
      categoria: 'accesorio', acabado: 'A juego', color: 'Variable',
      precio: 260, unidad: 'pza', stock: 320, leadTimeDias: 4,
      caracteristicas: ['Tramo de 0.90 m'] }),

  P({ id: 'ACC-NARIZ-ESC', sku: 'ACC-NARIZ-ESC', nombreEn: 'Stair Nosing Profile',
      nombre: 'Nariz de escalón con antiderrapante',
      categoria: 'accesorio', acabado: 'A juego con inserto', color: 'Variable',
      precio: 680, unidad: 'pza', stock: 140, leadTimeDias: 8,
      caracteristicas: ['Tramo de 1.20 m', 'Inserto antiderrapante'],
      notas: 'Obligatorio en escaleras de uso público por norma de accesibilidad.' }),

  P({ id: 'ACC-NIVEL', sku: 'ACC-NIVEL', nombreEn: 'Self-Leveling Compound 20 kg',
      nombre: 'Nivelante autonivelante 20 kg',
      categoria: 'accesorio', acabado: 'Saco', color: 'Gris',
      precio: 480, unidad: 'pza', stock: 260, leadTimeDias: 3,
      caracteristicas: ['Rendimiento 4 m² a 3 mm', 'Fraguado 4 horas'] }),

  P({ id: 'ACC-CUNAS', sku: 'ACC-CUNAS', nombreEn: 'Tile Leveling Clips and Wedges',
      nombre: 'Sistema de niveladores de cuña (100 pz)',
      categoria: 'accesorio', acabado: 'Bolsa', color: 'Naranja',
      precio: 320, unidad: 'pza', stock: 180, leadTimeDias: 3,
      caracteristicas: ['Obligatorio en gran formato'] }),

  P({ id: 'ACC-RIEL-CURV', sku: 'ACC-RIEL-CURV', nombreEn: 'Curved Curtain Track',
      nombre: 'Riel curvo hecho a medida',
      categoria: 'accesorio', acabado: 'Aluminio anodizado', color: 'Blanco',
      precio: 1450, unidad: 'ml', stock: 0, leadTimeDias: 15,
      caracteristicas: ['A medida', 'Para ventanal en curva o esquina'],
      notas: 'Se fabrica con plantilla del sitio. Cotizar levantamiento aparte.' }),

  P({ id: 'ACC-CENEFA', sku: 'ACC-CENEFA', nombreEn: 'Fabric Wrapped Valance / Cornice',
      nombre: 'Cenefa forrada en tela',
      categoria: 'accesorio', acabado: 'Forrada a juego', color: 'Variable',
      precio: 890, unidad: 'ml', stock: 0, leadTimeDias: 15,
      caracteristicas: ['Oculta el herraje', 'Acabado de alta gama'] }),

  P({ id: 'ACC-CONTROL', sku: 'ACC-CONTROL', nombreEn: 'Multi-Channel Remote Control',
      nombre: 'Control remoto multicanal (15 canales)',
      categoria: 'accesorio', acabado: 'Radiofrecuencia', color: 'Blanco',
      precio: 2400, unidad: 'pza', stock: 48, importado: true, origen: 'Francia',
      leadTimeDias: 30,
      caracteristicas: ['Hasta 15 equipos', 'Escenas programables'] }),

  P({ id: 'ACC-HUB-DOM', sku: 'ACC-HUB-DOM', nombreEn: 'Smart Home Bridge / Hub',
      nombre: 'Puente de domótica para control por app',
      categoria: 'accesorio', acabado: 'Wi-Fi', color: 'Blanco',
      precio: 6900, unidad: 'pza', stock: 22, importado: true, origen: 'Francia',
      leadTimeDias: 30,
      caracteristicas: ['Control por app', 'Compatible con asistentes de voz', 'Horarios automáticos'],
      notas: 'Un solo puente controla toda la casa. No cotizar uno por ventana.' }),

  P({ id: 'ACC-LIMP-KIT', sku: 'ACC-LIMP-KIT', nombreEn: 'Floor Care and Cleaning Kit',
      nombre: 'Kit de limpieza y mantenimiento de piso',
      categoria: 'accesorio', acabado: 'Kit', color: 'Incoloro',
      precio: 1180, unidad: 'pza', stock: 90, leadTimeDias: 5,
      caracteristicas: ['Jabón neutro', 'Mopa de microfibra', 'Reparador de rayones'],
      notas: 'Regalarlo al cierre cuesta poco y evita reclamaciones por limpieza indebida.' }),
];
